# Generated by Django 5.1.3 on 2025-01-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_details', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[('pending', 'Payment is yet to be completed.'), ('complete', 'Payment has been successfully completed.'), ('failed', 'Payment was unsuccessful.'), ('refunded', 'Payment has been refunded to the customer.')], default=('pending', 'Payment is yet to be completed.'), max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order_details.orderdetails', verbose_name='Amount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order_details.orderdetails')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
